on: [push, pull_request, workflow_dispatch]

name: helix-bluemicro840v1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build helix Left
        run: west build -s zmk/app -b bluemicro840_v1 -- -DSHIELD=helix_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      
      - name: helix DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/bluemicro840_v1.dts.pre.tmp
      
      - name: helix Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 helix_left_bluemicro840v1.uf2
      - name: Archive (helix Left)
        uses: actions/upload-artifact@v2
        with:
          name: helix
          path: helix_left_bluemicro840v1.uf2

      - name: West Build (helix Right)
        run: west build --pristine -s zmk/app -b bluemicro840_v1 -- -DSHIELD=helix_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: helix Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 helix_right_bluemicro840v1.uf2
      - name: Archive (helix Right)
        uses: actions/upload-artifact@v2
        with:
          name: helix
          path: helix_right_bluemicro840v1.uf2
