on: [workflow_dispatch]

name: soflergb-nicenano

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (sofleRGB Left)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=soflergb_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: sofleRGB DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: sofleRGB Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 soflergb_left_nice_nano.uf2
      - name: Archive (sofleRGB Left)
        uses: actions/upload-artifact@v2
        with:
          name: sofleRGB left
          path: soflergb_left_nice_nano.uf2
      - name: West Build (SofleRGB Right)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=soflergb_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: sofleRGB Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 soflergb_right_nice_nano.uf2
      - name: Archive (sofleRGB Right)
        uses: actions/upload-artifact@v2
        with:
          name: sofleRGB right
          path: soflergb_right_nice_nano.uf2
